# Site settings
name: Bharath Kumar Kancharla
email: bharathkumar.kancharla@gmail.com
url: 
description: "Series of blogs to explain the concept of deep learning in various fields like Computer Vision, Natural Learning processing etc.,"
author: "author"
title: "Deep Learning World"
permalink: pretty
baseurl: /

# social
github:
  username: bharathkumar-kancharla
